### PR TITLE
chore: update Nextcloud to 27.1.5

### PR DESCRIPTION
**Pull request by waja**

### CODE REVIEW

**Comment by hoellen** [comment]
Thanks

**Comment by waja** [comment]
https://github.com/hoellen/docker-nextcloud/pkgs/container/nextcloud/versions?filters%5Bversion_type%5D=tagged misses 27.1.5, maybe you can trigger a build. thank!

**Comment by hoellen** [comment]
I forgot to update the build script in the new branch. The new version is now available.

**Comment by waja** [comment]
> I forgot to update the build script in the new branch. The new version is now available.

I've prepared https://github.com/hoellen/docker-nextcloud/pull/57 for you, maybe it's handy.

**Pull request merged**
